version: '3.8'
services:
  quanta-admin-api:
    build: .
    container_name: quanta-admin
    privileged: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/:/quanta-admin/config/
      - ./static/:/quanta-admin/static/
      - ./temp/:/quanta-admin/temp/
    networks:
      - myweb
    environment:
      - LARK_WEBHOOK=${LARK_WEBHOOK}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - JWT_SECRET=${JWT_SECRET}

networks:
  myweb:
    driver: bridge

