version: '3.8'
services:
  quanta-admin-api:
    container_name: quanta-admin
    image: quanta-admin:latest
    privileged: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/:/quanta-admin/config/
      - ./static/:/quanta-admin/static/
      - ./temp/:/quanta-admin/temp/
#    networks:
#      - myweb
    environment:
      - LARK_WEBHOOK=${LARK_WEBHOOK}

#networks:
#  myweb:
#    driver: bridge

