version: '3.8'
services:
  quanta-admin-api:
    container_name: quanta-admin
    image: quanta-admin:latest
    privileged: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/:/quanta-admin-api/config/
      - ./static/:/quanta-admin-api/static/
      - ./temp/:/quanta-admin-api/temp/
    networks:
      - myweb
networks:
  myweb:
    driver: bridge

