version: '3.8'
services:
  quanta-admin-api:
    container_name: quanta-admin
    image: quanta-admin:latest
    privileged: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/:/quanta-admin-api/config/
      - ./static/:/quanta-admin-api/static/
      - ./temp/:/quanta-admin-api/temp/
    networks:
      - myweb
    environment:
#      - LARK_WEBHOOK=https://open.larksuite.com/open-apis/bot/v2/hook/d3eec5d3-d60f-46c2-84c5-93a2e4d8a4f3
      - LARK_WEBHOOK=${LARK_WEBHOOK}

networks:
  myweb:
    driver: bridge

