version: '3.8'
services:
  quanta-admin-api:
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}  # 通过 build argument 传递环境变量
    container_name: quanta-admin
    privileged: true
    restart: always
    ports:
      - 8002:8002
    volumes:
      - ./config/:/quanta-admin/config/
      - ./static/:/quanta-admin/static/
      - ./temp/:/quanta-admin/temp/
#    networks:
#      - myweb
    environment:
      - LARK_WEBHOOK=${LARK_WEBHOOK}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - JWT_SECRET=${JWT_SECRET}
      - ENVIRONMENT=staging  # 添加环境变量来区分环境

#networks:
#  myweb:
#    driver: bridge

