// proto/trigger_service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: trigger_service.proto

package trigger_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TriggerInstance_StartInstance_FullMethodName = "/grpc_service.TriggerInstance/StartInstance"
	TriggerInstance_ListInstances_FullMethodName = "/grpc_service.TriggerInstance/ListInstances"
)

// TriggerInstanceClient is the client API for TriggerInstance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TriggerInstanceClient interface {
	// 开启实例
	StartInstance(ctx context.Context, in *StartTriggerRequest, opts ...grpc.CallOption) (*StartTriggerResponse, error)
	// 暂停实例
	//
	//	rpc StopInstance (StopInstanceRequest) returns (google.protobuf.Empty);
	//
	// 查看所有启动的实例ids
	ListInstances(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TriggerListResponse, error)
}

type triggerInstanceClient struct {
	cc grpc.ClientConnInterface
}

func NewTriggerInstanceClient(cc grpc.ClientConnInterface) TriggerInstanceClient {
	return &triggerInstanceClient{cc}
}

func (c *triggerInstanceClient) StartInstance(ctx context.Context, in *StartTriggerRequest, opts ...grpc.CallOption) (*StartTriggerResponse, error) {
	out := new(StartTriggerResponse)
	err := c.cc.Invoke(ctx, TriggerInstance_StartInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerInstanceClient) ListInstances(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TriggerListResponse, error) {
	out := new(TriggerListResponse)
	err := c.cc.Invoke(ctx, TriggerInstance_ListInstances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriggerInstanceServer is the server API for TriggerInstance service.
// All implementations must embed UnimplementedTriggerInstanceServer
// for forward compatibility
type TriggerInstanceServer interface {
	// 开启实例
	StartInstance(context.Context, *StartTriggerRequest) (*StartTriggerResponse, error)
	// 暂停实例
	//
	//	rpc StopInstance (StopInstanceRequest) returns (google.protobuf.Empty);
	//
	// 查看所有启动的实例ids
	ListInstances(context.Context, *emptypb.Empty) (*TriggerListResponse, error)
	mustEmbedUnimplementedTriggerInstanceServer()
}

// UnimplementedTriggerInstanceServer must be embedded to have forward compatible implementations.
type UnimplementedTriggerInstanceServer struct {
}

func (UnimplementedTriggerInstanceServer) StartInstance(context.Context, *StartTriggerRequest) (*StartTriggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedTriggerInstanceServer) ListInstances(context.Context, *emptypb.Empty) (*TriggerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedTriggerInstanceServer) mustEmbedUnimplementedTriggerInstanceServer() {}

// UnsafeTriggerInstanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriggerInstanceServer will
// result in compilation errors.
type UnsafeTriggerInstanceServer interface {
	mustEmbedUnimplementedTriggerInstanceServer()
}

func RegisterTriggerInstanceServer(s grpc.ServiceRegistrar, srv TriggerInstanceServer) {
	s.RegisterService(&TriggerInstance_ServiceDesc, srv)
}

func _TriggerInstance_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerInstanceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriggerInstance_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerInstanceServer).StartInstance(ctx, req.(*StartTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TriggerInstance_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerInstanceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriggerInstance_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerInstanceServer).ListInstances(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TriggerInstance_ServiceDesc is the grpc.ServiceDesc for TriggerInstance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TriggerInstance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_service.TriggerInstance",
	HandlerType: (*TriggerInstanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartInstance",
			Handler:    _TriggerInstance_StartInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _TriggerInstance_ListInstances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trigger_service.proto",
}
